#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# build-notes.sh — turn notes/_content/*.html into full pages in notes/
#
#   bash tools/build-notes.sh
#
# Each source file carries a metadata comment at the top and the article body
# below it. The chrome — head, masthead, hero, author card, footer — comes from
# blog-post-template.html, so a change to the template reaches every post.
#
# WHY A SCRIPT AND NOT A CMS
# The CMS is coming and these posts will move into Supabase. Until then this
# keeps eight pages consistent without eight copies of the same markup drifting
# apart. The generated files are real static HTML, which is what makes them
# index well.
# ---------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="notes/_content"
OUT="notes"
TPL="blog-post-template.html"

# Must match SITE_URL in tools/build-seo.sh.
SITE="https://twelvepointrealty.com"

[ -d "$SRC" ] || { echo "no $SRC"; exit 1; }
[ -f "$TPL" ] || { echo "no $TPL"; exit 1; }

meta() {   # meta <file> <key>
  sed -n '/^<!--$/,/^-->$/p' "$1" | sed -n "s/^$2: //p" | head -1
}

count=0
for f in "$SRC"/*.html; do
  [ -e "$f" ] || continue
  slug="$(basename "$f" .html)"

  title="$(meta "$f" title)"
  cat="$(meta "$f" cat)"
  date="$(meta "$f" date)"
  read_time="$(meta "$f" read)"
  excerpt="$(meta "$f" excerpt)"
  image="$(meta "$f" image)"
  alt="$(meta "$f" alt)"
  # "August 2026" -> "2026-08-01" for the Article datePublished
  iso="$(date -d "1 $date" +%Y-%m-%d 2>/dev/null || echo 2026-08-01)"

  body="$(mktemp)"
  sed '1,/^-->$/d' "$f" > "$body"

  out="$OUT/$slug.html"
  tmp="$(mktemp)"

  # Swap the template's sample content for this post's.
  awk -v title="$title" -v cat="$cat" -v date="$date" -v rt="$read_time" \
      -v excerpt="$excerpt" -v image="$image" -v alt="$alt" -v bodyfile="$body" '
    # <title> and meta description
    /<title>/ && !t { print "<title>" title " — TwelvePoint Realty Group</title>"; t=1; next }
    /<meta name="description"/ && !d { print "<meta name=\"description\" content=\"" excerpt "\">"; d=1; next }
    # headline
    /<h1 class="h2"/ { print "      <h1 class=\"h2\" style=\"max-width:26ch\">" title "</h1>"; next }
    # the postmeta row directly under the headline
    /<span class="postmeta__cat">/ && !pm { print "        <span class=\"postmeta__cat\">" cat "</span>"; print "        <span>" date "</span>"; print "        <span>" rt "</span>"; pm=1; skipmeta=1; next }
    skipmeta && /<\/div>/ { skipmeta=0; print; next }
    skipmeta { next }
    # hero image
    /fetchpriority="high"/ && /<img/ { print "      <img width=\"960\" height=\"720\" src=\"/" image "\" alt=\"" alt "\" style=\"width:100%;aspect-ratio:16/9;object-fit:cover\" fetchpriority=\"high\">"; next }
    # article body
    /<div class="prose">/ { print; inprose=1; while ((getline l < bodyfile) > 0) print l; close(bodyfile); next }
    inprose && /^      <\/div>$/ { inprose=0; print; next }
    inprose { next }
    { print }
  ' "$TPL" > "$tmp"

  # Relative asset paths break one directory down.
  sed -i 's|href="assets/|href="/assets/|g; s|src="assets/|src="/assets/|g' "$tmp"
  for p in index listings buyers home-value team blog join login agent-austin agent-karsyn; do
    sed -i "s|href=\"$p.html|href=\"/$p.html|g" "$tmp"
  done
  sed -i 's|href="favicon.ico"|href="/favicon.ico"|g' "$tmp"


  # The template carries a generated SEO block that says noindex and points
  # its canonical at the template itself. Inheriting that would make every
  # note invisible to search — the exact opposite of why this section exists.
  # Replace it with the post's own, including Article schema, which is now
  # honest because these are real articles rather than placeholders.
  seo="$(mktemp)"
  {
    echo "<!-- SEO:START — generated by tools/build-notes.sh. Do not edit here. -->"
    echo "<link rel=\"canonical\" href=\"$SITE/notes/$slug.html\">"
    echo "<meta name=\"robots\" content=\"index, follow, max-image-preview:large, max-snippet:-1\">"
    echo "<meta property=\"og:type\" content=\"article\">"
    echo "<meta property=\"og:url\" content=\"$SITE/notes/$slug.html\">"
    echo "<meta property=\"og:site_name\" content=\"TwelvePoint Realty Group\">"
    echo "<meta property=\"og:locale\" content=\"en_US\">"
    echo "<meta property=\"og:title\" content=\"$title\">"
    echo "<meta property=\"og:description\" content=\"$excerpt\">"
    echo "<meta property=\"og:image\" content=\"$SITE/$image\">"
    echo "<meta name=\"twitter:card\" content=\"summary_large_image\">"
    echo "<meta name=\"twitter:image\" content=\"$SITE/$image\">"
    echo "<script type=\"application/ld+json\">"
    echo "{"
    echo "  \"@context\": \"https://schema.org\","
    echo "  \"@type\": \"Article\","
    echo "  \"headline\": \"$title\","
    echo "  \"description\": \"$excerpt\","
    echo "  \"image\": \"$SITE/$image\","
    echo "  \"datePublished\": \"$iso\","
    echo "  \"inLanguage\": \"en-US\","
    echo "  \"mainEntityOfPage\": { \"@type\": \"WebPage\", \"@id\": \"$SITE/notes/$slug.html\" },"
    echo "  \"author\": { \"@type\": \"Person\", \"name\": \"Austin Eggers\", \"url\": \"$SITE/agent-austin.html\" },"
    echo "  \"publisher\": { \"@id\": \"$SITE/#organization\" },"
    echo "  \"articleSection\": \"$cat\""
    echo "}"
    echo "</script>"
    echo "<!-- SEO:END -->"
  } > "$seo"
  awk -v sf="$seo" '
    index($0,"SEO:START") { while ((getline l < sf) > 0) print l; close(sf); skip=1; next }
    index($0,"SEO:END")   { skip=0; next }
    !skip { print }
  ' "$tmp" > "$tmp.seo" && mv "$tmp.seo" "$tmp"
  rm -f "$seo"
  if [ -f "$out" ] && cmp -s "$tmp" "$out"; then
    echo "  ok       $out"
  else
    mv "$tmp" "$out"
    echo "  built    $out"
  fi
  rm -f "$body" "$tmp" 2>/dev/null || true
  count=$((count+1))
done

echo "done — $count posts"
