#!/usr/bin/env bash
# =====================================================================
# build-seo.sh — stamps the domain-dependent SEO block into every page,
# then regenerates sitemap.xml and robots.txt.
#
#   bash tools/build-seo.sh            rewrite every page
#   bash tools/build-seo.sh --check    exit 1 if anything is out of date
#
# Everything that depends on the live domain lives in the generated
# region between the SEO:START / SEO:END markers, so changing SITE_URL
# below and re-running is the whole migration. Do not hand-edit inside
# the markers — this script overwrites it.
# =====================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

# --------------------------------------------------------------- config
# The live origin, no trailing slash. Change this one line when the
# domain is confirmed, re-run, and every canonical, og:url, absolute
# image URL, sitemap entry and JSON-LD @id follows.
SITE_URL="https://twelvepointrealty.com"

BRAND="TwelvePoint Realty Group"
BROKER="Goldmount Real Estate Group"
PHONE="+1-713-828-4185"
EMAIL="austin.eggers@gregtxrealty.com"
STREET="9595 Six Pines Drive"
CITY="The Woodlands"
REGION="TX"
ZIP="77380"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

START="<!-- SEO:START — generated by tools/build-seo.sh. Do not edit here. -->"
END="<!-- SEO:END -->"

# The org node every page points its publisher/provider at, so the whole
# site resolves to a single business entity rather than 13 unrelated ones.
org_node() {
  cat <<JSON
    {
      "@type": "RealEstateAgent",
      "@id": "${SITE_URL}/#organization",
      "name": "${BRAND}",
      "url": "${SITE_URL}/",
      "logo": "${SITE_URL}/assets/mark-ink.png",
      "image": "${SITE_URL}/assets/hero-oaks.jpg",
      "telephone": "${PHONE}",
      "email": "${EMAIL}",
      "parentOrganization": { "@type": "Organization", "name": "${BROKER}" },
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "${STREET}",
        "addressLocality": "${CITY}",
        "addressRegion": "${REGION}",
        "postalCode": "${ZIP}",
        "addressCountry": "US"
      },
      "areaServed": [
        { "@type": "City", "name": "Houston" },
        { "@type": "City", "name": "The Woodlands" },
        { "@type": "City", "name": "Cypress" },
        { "@type": "City", "name": "Tomball" },
        { "@type": "City", "name": "Spring" },
        { "@type": "City", "name": "Magnolia" },
        { "@type": "City", "name": "Conroe" }
      ],
      "sameAs": [
        "https://www.har.com/austin-eggers/agent_aeggers"
      ]
    }
JSON
}

# Breadcrumb for interior pages. $1 = page url path, $2 = page label.
crumbs() {
  cat <<JSON
  {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      { "@type": "ListItem", "position": 1, "name": "Home", "item": "${SITE_URL}/" },
      { "@type": "ListItem", "position": 2, "name": "$2", "item": "${SITE_URL}/$1" }
    ]
  }
JSON
}

# Three-level trail, for pages that render one on screen. The agent pages
# show "Team / Name", and breadcrumb markup has to match what a visitor sees.
crumbs3() {
  cat <<JSON
  {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      { "@type": "ListItem", "position": 1, "name": "Home", "item": "${SITE_URL}/" },
      { "@type": "ListItem", "position": 2, "name": "Team", "item": "${SITE_URL}/team.html" },
      { "@type": "ListItem", "position": 3, "name": "$2", "item": "${SITE_URL}/$1" }
    ]
  }
JSON
}

# ------------------------------------------------------- per-page JSON-LD
# Emitted inside the generated block. Anything factual here has to be
# backed by the page copy — no invented hours, ratings, or prices.
page_jsonld() {
  case "$1" in
    index.html)
      cat <<JSON
  {
    "@context": "https://schema.org",
    "@graph": [
$(org_node),
      {
        "@type": "WebSite",
        "@id": "${SITE_URL}/#website",
        "url": "${SITE_URL}/",
        "name": "${BRAND}",
        "inLanguage": "en-US",
        "publisher": { "@id": "${SITE_URL}/#organization" }
      }
    ]
  }
JSON
      ;;
    home-value.html)
      cat <<JSON
  {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      { "@type": "Question", "name": "Is the valuation free?",
        "acceptedAnswer": { "@type": "Answer", "text": "Yes — there is no cost and no obligation. It is how we introduce ourselves, and many of the people we prepare one for are not selling this year." } },
      { "@type": "Question", "name": "How is this different from an online estimate?",
        "acceptedAnswer": { "@type": "Answer", "text": "An automated estimate is built from public records and past sales. It cannot see condition, updates, lot position, or what is competing with your home right now. A licensed broker associate who works this market prepares yours by hand, and shows the reasoning." } },
      { "@type": "Question", "name": "Do I need to be ready to sell immediately?",
        "acceptedAnswer": { "@type": "Answer", "text": "No. Knowing where your home stands is useful whether you are listing next month or simply weighing options. Tell us your timeline on the form and we will treat it accordingly." } },
      { "@type": "Question", "name": "What information do you need about my property?",
        "acceptedAnswer": { "@type": "Answer", "text": "The address is enough to begin. Square footage, bedroom and bathroom count, condition, and any renovations make the range tighter — but leave blank anything you are unsure of." } },
      { "@type": "Question", "name": "Can renovations or upgrades affect my home's value?",
        "acceptedAnswer": { "@type": "Answer", "text": "Considerably, and not always in the direction people expect. Some improvements return most of their cost at resale and others return very little. Where it is relevant, the report flags which work is worth doing before listing." } },
      { "@type": "Question", "name": "What if my property is outside Houston?",
        "acceptedAnswer": { "@type": "Answer", "text": "We work Houston and the surrounding areas. Send the address and we will tell you honestly whether it is somewhere we know well enough to give you a useful answer." } }
    ]
  },
$(crumbs "home-value.html" "Home Value")
JSON
      ;;
    buyers.html)
      cat <<JSON
  {
    "@context": "https://schema.org",
    "@type": "Service",
    "name": "Buyer representation",
    "serviceType": "Real estate buyer representation",
    "provider": { "@id": "${SITE_URL}/#organization" },
    "areaServed": { "@type": "City", "name": "Houston" }
  },
$(crumbs "buyers.html" "Buyers")
JSON
      ;;
    listings.html)
      cat <<JSON
  {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "name": "Listings — ${BRAND}",
    "isPartOf": { "@id": "${SITE_URL}/#website" },
    "about": { "@id": "${SITE_URL}/#organization" }
  },
$(crumbs "listings.html" "Listings")
JSON
      ;;
    team.html)
      cat <<JSON
$(crumbs "team.html" "Team")
JSON
      ;;
    agent-austin.html)
      cat <<JSON
  {
    "@context": "https://schema.org",
    "@type": "Person",
    "@id": "${SITE_URL}/agent-austin.html#person",
    "name": "Austin Eggers",
    "jobTitle": "Broker Associate",
    "url": "${SITE_URL}/agent-austin.html",
    "image": "${SITE_URL}/assets/austin.jpg",
    "telephone": "${PHONE}",
    "email": "${EMAIL}",
    "worksFor": { "@id": "${SITE_URL}/#organization" },
    "sameAs": [ "https://www.har.com/austin-eggers/agent_aeggers" ]
  },
$(crumbs3 "agent-austin.html" "Austin Eggers")
JSON
      ;;
    agent-karsyn.html)
      cat <<JSON
  {
    "@context": "https://schema.org",
    "@type": "Person",
    "@id": "${SITE_URL}/agent-karsyn.html#person",
    "name": "Karsyn Adams",
    "url": "${SITE_URL}/agent-karsyn.html",
    "worksFor": { "@id": "${SITE_URL}/#organization" }
  },
$(crumbs3 "agent-karsyn.html" "Karsyn Adams")
JSON
      ;;
    blog.html)
      cat <<JSON
  {
    "@context": "https://schema.org",
    "@type": "Blog",
    "@id": "${SITE_URL}/blog.html#blog",
    "name": "Notes — ${BRAND}",
    "description": "Plain answers on buying and selling in Houston.",
    "inLanguage": "en-US",
    "publisher": { "@id": "${SITE_URL}/#organization" }
  },
$(crumbs "blog.html" "Notes")
JSON
      ;;
    join.html)
      cat <<JSON
$(crumbs "join.html" "Join the Team")
JSON
      ;;
    *) return 0 ;;
  esac
}

# ------------------------------------------------------------ page table
# file|url path|default share image|indexable
PAGES="
index.html|/|assets/hero-oaks.jpg|yes
listings.html|/listings.html|assets/property-ranch.jpg|yes
buyers.html|/buyers.html|assets/hero-oaks.jpg|yes
home-value.html|/home-value.html|assets/estate-drive.jpg|yes
team.html|/team.html|assets/hero-oaks.jpg|yes
agent-austin.html|/agent-austin.html|assets/austin.jpg|yes
agent-karsyn.html|/agent-karsyn.html|assets/hero-oaks.jpg|yes
blog.html|/blog.html|assets/property-sunset.jpg|yes
join.html|/join.html|assets/hero-oaks.jpg|yes
login.html|/login.html|assets/hero-oaks.jpg|no
idx-wrapper.html|/idx-wrapper.html|assets/hero-oaks.jpg|no
blog-post-template.html|/blog-post-template.html|assets/property-sunset.jpg|no
listing-template.html|/listing-template.html|assets/property-ranch.jpg|no
"

changed=0
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

emit_block() {
  local file="$1" path="$2" img="$3" index="$4"
  local canon="${SITE_URL}${path}"
  echo "$START"
  echo "<link rel=\"canonical\" href=\"${canon}\">"
  if [ "$index" = "no" ]; then
    echo "<meta name=\"robots\" content=\"noindex, nofollow\">"
  else
    echo "<meta name=\"robots\" content=\"index, follow, max-image-preview:large, max-snippet:-1\">"
  fi
  echo "<meta property=\"og:url\" content=\"${canon}\">"
  echo "<meta property=\"og:site_name\" content=\"${BRAND}\">"
  echo "<meta property=\"og:locale\" content=\"en_US\">"
  echo "<meta property=\"og:image\" content=\"${SITE_URL}/${img}\">"
  echo "<meta property=\"og:image:alt\" content=\"${BRAND}\">"
  echo "<meta name=\"twitter:card\" content=\"summary_large_image\">"
  echo "<meta name=\"twitter:image\" content=\"${SITE_URL}/${img}\">"
  if [ "$index" = "yes" ]; then
    local ld; ld="$(page_jsonld "$file" || true)"
    if [ -n "$ld" ]; then
      echo "<script type=\"application/ld+json\">"
      # Wrap multiple top-level nodes in @graph-free array form.
      if [ "$(printf '%s' "$ld" | grep -c '"@context"')" -gt 1 ]; then
        echo "["
        printf '%s\n' "$ld"
        echo "]"
      else
        printf '%s\n' "$ld"
      fi
      echo "</script>"
    fi
  fi
  echo "$END"
}

for row in $PAGES; do
  [ -z "$row" ] && continue
  file="${row%%|*}";  rest="${row#*|}"
  path="${rest%%|*}"; rest="${rest#*|}"
  img="${rest%%|*}"
  index="${rest##*|}"
  [ -f "$file" ] || { echo "skip (missing): $file"; continue; }

  work="$tmp/$file"
  # 1. drop any previously generated block
  awk -v s="SEO:START" -v e="SEO:END" '
    index($0,s){skip=1} !skip{print} index($0,e){skip=0}
  ' "$file" > "$work"
  # 2. drop tags the generated block now owns, wherever they were before
  sed -i -E '/<meta property="og:image" content="assets\//d;
             /<meta property="og:image" content="https?:\/\//d;
             /<meta name="twitter:card"/d;
             /<meta name="twitter:image"/d;
             /<meta name="robots"/d;
             /<link rel="canonical"/d' "$work"
  # 3. splice the fresh block in ahead of </head>
  emit_block "$file" "$path" "$img" "$index" > "$tmp/block"
  awk -v bf="$tmp/block" '
    /<\/head>/ && !done { while ((getline l < bf) > 0) print l; close(bf); done=1 }
    { print }
  ' "$work" > "$tmp/out"

  if cmp -s "$tmp/out" "$file"; then
    :
  else
    changed=1
    if [ "$CHECK" = "1" ]; then
      echo "OUT OF DATE: $file"
    else
      cp "$tmp/out" "$file"
      echo "seo: $file"
    fi
  fi
done

# --------------------------------------------------------------- sitemap
# Only indexable pages. lastmod comes from the file's own mtime, so it
# stays honest without anyone maintaining a date by hand.
build_sitemap() {
  {
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
    for row in $PAGES; do
      [ -z "$row" ] && continue
      file="${row%%|*}";  rest="${row#*|}"
      path="${rest%%|*}"
      index="${rest##*|}"
      [ "$index" = "yes" ] || continue
      [ -f "$file" ] || continue
      lastmod="$(date -u -r "$file" +%Y-%m-%d)"
      case "$path" in
        /)  prio="1.0" ;;
        /listings.html|/home-value.html|/buyers.html) prio="0.9" ;;
        *)  prio="0.7" ;;
      esac
      printf '  <url>\n    <loc>%s%s</loc>\n    <lastmod>%s</lastmod>\n    <priority>%s</priority>\n  </url>\n' \
        "$SITE_URL" "$path" "$lastmod" "$prio"
    done
    # Notes carry their own SEO block from tools/build-notes.sh; they are
    # listed here purely so search engines can discover them.
    for n in notes/*.html; do
      [ -e "$n" ] || continue
      lastmod="$(date -u -r "$n" +%Y-%m-%d)"
      printf '  <url>\n    <loc>%s/%s</loc>\n    <lastmod>%s</lastmod>\n    <priority>0.6</priority>\n  </url>\n' \
        "$SITE_URL" "$n" "$lastmod"
    done
    echo '</urlset>'
  }
}

build_robots() {
  cat <<TXT
User-agent: *
Allow: /

# Not useful in search results, and the templates would read as
# duplicate/thin content against the real pages they seed.
Disallow: /login.html
Disallow: /blog-post-template.html
Disallow: /listing-template.html

Sitemap: ${SITE_URL}/sitemap.xml
TXT
}

for pair in "sitemap.xml:build_sitemap" "robots.txt:build_robots"; do
  out="${pair%%:*}"; fn="${pair##*:}"
  "$fn" > "$tmp/gen"
  if cmp -s "$tmp/gen" "$out" 2>/dev/null; then
    :
  else
    changed=1
    if [ "$CHECK" = "1" ]; then echo "OUT OF DATE: $out"
    else cp "$tmp/gen" "$out"; echo "seo: $out"; fi
  fi
done

if [ "$CHECK" = "1" ]; then
  [ "$changed" = "1" ] && { echo "run: bash tools/build-seo.sh"; exit 1; }
  echo "SEO artifacts up to date."
fi
exit 0
